name: bawiki
label: Bashkir Wikipedia
host: ba.wikipedia.org

external_samples:
  sampled_revisions.60k_2018:
    quarry_page: https://quarry.wmflabs.org/query/24777
    quarry_url: https://quarry.wmflabs.org/run/236209/output/0/json-lines?download=true

autolabeled_samples:
  trusted_edits: 1000
  trusted_groups:
   - bot
   - sysop
   - bureaucrat
  labeled_samples:
    autolabeled_revisions.60k_2018: sampled_revisions.60k_2018



