name: bnwikisource
label: Bengali Wikisource
host: bn.wikisource.org

external_samples:
  sampled_revisions.200k_2018:
    quarry_page: https://quarry.wmflabs.org/query/24776
    quarry_url: https://quarry.wmflabs.org/run/236208/output/0/json-lines?download=true

autolabeled_samples:
  trusted_edits: 1000
  trusted_groups:
   - bot
   - sysop
  labeled_samples:
    autolabeled_revisions.200k_2018: sampled_revisions.200k_2018



