name: bswiki
label: Bosnian Wikipedia
host: bs.wikipedia.org

external_samples:
  sampled_revisions.40k_2018:
    quarry_page: https://quarry.wmflabs.org/query/26936
    quarry_url: https://quarry.wmflabs.org/run/261117/output/0/json-lines?download=true
  human_labeled_revisions.5k_2018:
    labeling_campaign: https://labels.wmflabs.org/campaigns/bswiki/78/

autolabeled_samples:
  trusted_edits: 1000
  trusted_groups:
   - bot
   - sysop
   - bureaucrat
  labeled_samples:
    autolabeled_revisions.40k_2018: sampled_revisions.40k_2018

merged_samples:
  labeled_revisions.40k_2018:
    - human_labeled_revisions.5k_2018
    - autolabeled_revisions.40k_2018

extracted_samples:
  labeled_revisions.w_cache.40k_2018:
    sample: labeled_revisions.40k_2018
    features_for:
      - damaging
      - goodfaith

models:
  damaging:
    observations: labeled_revisions.w_cache.40k_2018
    label: damaging
    pop_rate_true: 0.028101164191087918
    tune: true
    cv_train:
      algorithm: RandomForest
      parameters:
        criterion: entropy
        max_features: log2
        min_samples_leaf: 7
        n_estimators: 320
  goodfaith:
    observations: labeled_revisions.w_cache.40k_2018
    label: goodfaith
    pop_rate_true: 0.9774939783219591
    tune: true
    cv_train:
      algorithm: GradientBoosting
      parameters:
        learning_rate: 0.5
        max_depth: 7
        max_features: log2
        n_estimators: 700
