name: enwiki
label: English Wikipedia
host: en.wikipedia.org

external_samples:
  labeled_revisions.20k_2015:
    labeling_campaign: https://labels.wmflabs.org/campaigns/enwiki/4/

autolabeled_samples:
  trusted_edits: 1000
  trusted_groups:
   - sysop
   - oversight
   - bot
   - rollbacker
   - checkuser
   - abusefilter
   - bureaucrat
  labeled_samples: {}

extracted_samples:
  labeled_revisions.w_cache.20k_2015:
    sample: labeled_revisions.20k_2015
    features_for:
      - damaging
      - goodfaith

models:
  damaging:
    label: damaging
    pop_rate_true: 0.034163555464634586
    tune: true
    cv_train:
      algorithm: GradientBoosting
      parameters:
        learning_rate: 0.01
        max_depth: 7
        max_features: log2
        n_estimators: 700
  goodfaith:
    label: goodfaith
    pop_rate_true: 0.9671661637600368
    tune: true
    cv_train:
      algorithm: GradientBoosting
      parameters:
        learning_rate: 0.01
        max_depth: 7
        max_features: log2
        n_estimators: 700
