name: enwiktionary
label: English Wiktionary
host: en.wiktionary.org

external_samples:
  sampled_revisions.92k_2018:
    quarry_url: https://quarry.wmflabs.org/run/244906/output/0/json-lines?download=true

autolabeled_samples:
  trusted_edits: 1000
  trusted_groups:
   - sysop
   - oversight
   - bot
   - rollbacker
   - checkuser
   - abusefilter
   - bureaucrat
  labeled_samples:
    autolabeled_revisions.92k_2018: sampled_revisions.92k_2018

extracted_samples:
  autolabeled_revisions.w_cache.92k_2018:
    sample: autolabeled_revisions.92k_2018
    features_for:
      - reverted

models:
  reverted:
    observations: autolabeled_revisions.w_cache.92k_2018
    label: reverted_for_damage
    pop_rate_true: 0.004778273117085203
    tune: true
    cv_train:
      algorithm: RandomForest
      parameters:
        criterion: entropy
        max_features: log2
        min_samples_leaf: 3
        n_estimators: 320
