name: enwiki
label: English Wikipedia
host: en.wikipedia.org

external_samples:
  human_labeled_revisions.20k_2015:
    labeling_campaign: https://labels.wmflabs.org/campaigns/enwiki/4/
  sampled_revisions.20k_2016:
    quarry_page: https://quarry.wmflabs.org/query/11963
    quarry_url: https://quarry.wmflabs.org/run/109211/output/0/json-lines
  human_labeled_revisions.5k_2016:
    labeling_campaign: https://labels.wmflabs.org/campaigns/enwiki/41/

autolabeled_samples:
  trusted_edits: 1000
  trusted_groups:
   - sysop
   - oversight
   - bot
   - rollbacker
   - checkuser
   - abusefilter
   - bureaucrat
  labeled_samples:
    autolabeled_revisions.20k_2016: sampled_revisions.20k_2016

merged_samples:
  labeled_revisions.20k_2015:
    - human_labeled_revisions.20k_2015
  labeled_revisions.20k_2016:
    - human_labeled_revisions.5k_2016
    - autolabeled_revisions.20k_2016

extracted_samples:
  labeled_revisions.w_cache.20k_2015:
    sample: labeled_revisions.20k_2015
    features_for:
      - damaging
      - goodfaith
  labeled_revisions.w_cache.20k_2016:
    sample: labeled_revisions.20k_2016
    features_for:
      - damaging
      - goodfaith

models:
  damaging:
    observations: labeled_revisions.w_cache.20k_2015
    label: damaging
    pop_rate_true: 0.034163555464634586
    tune: true
    cv_train:
      algorithm: GradientBoosting
      parameters:
        learning_rate: 0.01
        max_depth: 7
        max_features: log2
        n_estimators: 700
  goodfaith:
    observations: labeled_revisions.w_cache.20k_2015
    label: goodfaith
    pop_rate_true: 0.9671661637600368
    tune: true
    cv_train:
      algorithm: GradientBoosting
      parameters:
        learning_rate: 0.01
        max_depth: 7
        max_features: log2
        n_estimators: 700
