name: eswikiquote
label: Spanish Wikiquote
host: es.wikiquote.org

external_samples:
  sampled_revisions.12k_2017:
    quarry_page: https://quarry.wmflabs.org/query/23421
    quarry_url: https://quarry.wmflabs.org/run/219894/output/0/json-lines?download=true
  human_labeled_revisions.5k_2017:
    labeling_campaign: https://labels.wmflabs.org/campaigns/eswikiquote/64/

autolabeled_samples:
  trusted_edits: 1000
  trusted_groups:
   - sysop
   - oversight
   - bot
   - rollbacker
   - checkuser
   - abusefilter
   - bureaucrat
   - autopatrolled
  labeled_samples:
    autolabeled_revisions.12k_2017: sampled_revisions.12k_2017

merged_samples:
  labeled_revisions.12k_2017:
    - autolabeled_revisions.12k_2017
    - human_labeled_revisions.5k_2017

extracted_samples:
  labeled_revisions.w_cache.12k_2017:
    sample: labeled_revisions.12k_2017
    features_for:
      - damaging
      - goodfaith

models:
  damaging:
    observations: labeled_revisions.w_cache.12k_2017
    label: damaging
    pop_rate_true: 0.08707101597009854
    tune: true
    cv_train:
      algorithm: GradientBoosting
      parameters:
        learning_rate: 0.01
        max_depth: 7
        max_features: log2
        n_estimators: 700
  goodfaith:
    observations: labeled_revisions.w_cache.12k_2017
    label: goodfaith
    pop_rate_true: 0.9356099218484539
    tune: true
    cv_train:
      algorithm: GradientBoosting
      parameters:
        learning_rate: 1
        max_depth: 7
        max_features: log2
        n_estimators: 700
