name: ptwiki
label: Portugueses Wikipedia
host: pt.wikipedia.org

external_samples:
  human_labeled_revisions.20k_2015:
    labeling_campaign: https://labels.wmflabs.org/campaigns/ptwiki/7/

merged_samples:
  labeled_revisions.20k_2015:
    - human_labeled_revisions.20k_2015

extracted_samples:
  labeled_revisions.w_cache.20k_2015:
    sample: labeled_revisions.20k_2015
    features_for:
      - damaging
      - goodfaith

models:
  damaging:
    observations: labeled_revisions.w_cache.20k_2015
    label: damaging
    pop_rate_true: 0.06896029864299047
    tune: true
    cv_train:
      algorithm: GradientBoosting
      parameters:
        learning_rate: 0.01
        max_depth: 7
        max_features: log2
        n_estimators: 700
  goodfaith:
    observations: labeled_revisions.w_cache.20k_2015
    label: goodfaith
    pop_rate_true: 0.9397669373959542
    tune: true
    cv_train:
      algorithm: GradientBoosting
      parameters:
        learning_rate: 0.01
        max_depth: 7
        max_features: log2
        n_estimators: 700
