name: rowiki
label: Romanian Wikipedia
host: ro.wikipedia.org

external_samples:
  sampled_revisions.20k_2016:
    quarry_url: https://quarry.wmflabs.org/run/146926/output/0/json-lines?download=true
  human_labeled_revisions.5k_2016:
    labeling_campaign: https://labels.wmflabs.org/campaigns/rowiki/48/

autolabeled_samples:
  trusted_edits: 1000
  trusted_groups:
   - abusefilter
   - arbcom
   - bureaucrat
   - checkuser
   - rollbacker
   - sysop
   - bot
   - templateeditor
   - patroller
   - autopatrolled
  labeled_samples:
    autolabeled_revisions.20k_2016: sampled_revisions.20k_2016

merged_samples:
  labeled_revisions.20k_2016:
    - autolabeled_revisions.20k_2016
    - human_labeled_revisions.5k_2016

extracted_samples:
  labeled_revisions.w_cache.20k_2016:
    sample: labeled_revisions.20k_2016
    features_for:
      - damaging
      - goodfaith

models:
  damaging:
    observations: labeled_revisions.w_cache.20k_2016
    label: damaging
    pop_rate_true: 0.04956982793117247
    tune: true
    cv_train:
      algorithm: GradientBoosting
      parameters:
        learning_rate: 0.01
        max_depth: 5
        max_features: log2
        n_estimators: 700
  goodfaith:
    observations: labeled_revisions.w_cache.20k_2016
    label: goodfaith
    pop_rate_true: 0.9699379751900761
    tune: true
    cv_train:
      algorithm: GradientBoosting
      parameters:
        learning_rate: 0.1
        max_depth: 3
        max_features: log2
        n_estimators: 300
