name: srwiki
label: Serbian Wikipedia
host: sr.wikipedia.org

external_samples:
  sampled_revisions.120k_2017:
    quarry_url: https://quarry.wmflabs.org/run/211097/output/0/json-lines?download=true
  human_labeled_revisions.5k_2017:
    labeling_campaign: https://labels.wmflabs.org/campaigns/srwiki/62/
  badfaith_relabeling_revisions.500_2017:
    labeling_campaign: https://labels.wmflabs.org/campaigns/srwiki/89/

autolabeled_samples:
  trusted_edits: 1000
  trusted_groups:
   - autopatrolled
   - bot
   - bureaucrat
   - patroller
   - rollbacker
   - sysop
  labeled_samples:
    autolabeled_revisions.120k_2017: sampled_revisions.120k_2017

merged_samples:
  original_labeled_revisions.120k_2017:
    - human_labeled_revisions.5k_2017
    - autolabeled_revisions.120k_2017
  labeled_revisions.120k_2017:
    - badfaith_relabeling_revisions.500_2017
    - original_labeled_revisions.120k_2017

extracted_samples:
  labeled_revisions.w_cache.120k_2017:
    sample: labeled_revisions.120k_2017
    features_for:
      - damaging
      - goodfaith

models:
  damaging:
    observations: labeled_revisions.w_cache.120k_2017
    label: damaging
    pop_rate_true: 0.0056294177044766075
    tune: true
    cv_train:
      algorithm: GradientBoosting
      build_number: 1
      parameters:
        learning_rate: 0.01
        max_depth: 7
        max_features: log2
        n_estimators: 700
  goodfaith:
    observations: labeled_revisions.w_cache.120k_2017
    label: goodfaith
    pop_rate_true: 0.9961881521373275
    tune: true
    cv_train:
      algorithm: GradientBoosting
      build_number: 1
      parameters:
        learning_rate: 0.01
        max_depth: 5
        max_features: log2
        n_estimators: 500
