name: ukwiki
label: Ukranian Wikipedia
host: uk.wikipedia.org

external_samples:
  sampled_revisions.20k_2015:
    quarry_url: http://quarry.wmflabs.org/run/48597/output/0/json-lines?download=true

autolabeled_samples:
  trusted_edits: 1000
  trusted_groups:
   - abusefilter
   - arbcom
   - bureaucrat
   - checkuser
   - rollbacker
   - sysop
   - bot
  labeled_samples:
    autolabeled_revisions.20k_2015: sampled_revisions.20k_2015

extracted_samples:
  labeled_revisions.w_cache.20k_2015:
    sample: labeled_revisions.20k_2015
    features_for:
      - reverted

models:
  reverted:
    observations: labeled_revisions.w_cache.20k_2015
    label: reverted_for_damage
    pop_rate_true: 0.021877665713282153
    tune: true
    cv_train:
      algorithm: GradientBoosting
      parameters:
        learning_rate: 0.01
        max_depth: 7
        max_features: log2
        n_estimators: 700
