name: urwiki
label: Urdu Wikipedia
host: ur.wikipedia.org

external_samples:
  sampled_revisions.500k_2015:
    quarry_url: http://quarry.wmflabs.org/run/64277/output/0/json-lines?download=true

autolabeled_samples:
  trusted_edits: 1000
  trusted_groups:
   - bot
   - bureaucrat
   - sysop
   - rollbackers
  labeled_samples:
    autolabeled_revisions.500k_2015: sampled_revisions.500k_2015

balanced_5k_samples:
  revisions_for_review.5k_2015: autolabeled_revisions.500k_2015
