name: viwiki
label: Vietnamese Wikipedia
host: vi.wikipedia.org

external_samples:
  sampled_revisions.500k_2015:
    quarry_url: http://quarry.wmflabs.org/run/65793/output/0/json-lines?download=true

autolabeled_samples:
  trusted_edits: 1000
  trusted_groups:
   - checkuser
   - bureaucrat
   - sysop
   - eliminator
   - bot
  labeled_samples:
    autolabeled_revisions.500k_2015: sampled_revisions.500k_2015

balanced_5k_samples:
  revisions_for_review.5k_2015: autolabeled_revisions.500k_2015

extracted_samples:
  labeled_revisions.w_cache.500k_2015:
    sample: labeled_revisions.500k_2015
    features_for:
      - reverted

models:
  reverted:
    observations: labeled_revisions.w_cache.500k_2015
    label: reverted_for_damage
    pop_rate_true: 0.019211042993949594
    tune: true
    cv_train:
      algorithm: GradientBoosting
      parameters:
        learning_rate: 0.01
        max_depth: 7
        max_features: log2
        n_estimators: 700
